### ISSUE TITLE
When using downloadFromInfo got [ WARNING ]: Specify poToken for stable and fast operation. See README for details.

### ISSUE THREAD

**Issue by gabrielstuff** [ybd-project/ytdl-core#10] opened 2024-09-05 08:09 UTC
Hello and thanks for this amazing work. Youtube is not easy on us 😅

## Describe the bug

The app is initialized with `poToken` and `visitorData`, but when using `downloadFromInfo` it seems that they are missing.
It indicates:

```
[ WARNING ]: Specify poToken for stable and fast operation. See README for details.
[  INFO!  ]: Automatically generates poToken, but stable operation cannot be guaranteed.
```

I'm calling this way : 

```
const stream = ytdl
      .downloadFromInfo(info, { quality })
      .on('progress', (chunkLength, downloaded, total) => {
        const percent = (downloaded / total) * 100
        throttleStateUpdate(`downloading ${percent.toFixed(2)}%`, id)
      })
      .pipe(createWriteStream(outputPath))
      .on('finish', () => resolve())
      .on('error', (error) => reject(error))
  })
```

The call to `basicInfo` works fine.

```
const basicInfo = await ytdl.getBasicInfo(
  '[http://www.youtube.com/watch?v=aqz-KE-bpKQ'](https://www.youtube.com/watch?si=RGj8VD51j4-mQZ5w&v=iT_e4-gXLt0&feature=youtu.be),
  {
    poToken: poToken,
    visitorData: visitorData
  }
)
```

## Error Details (Log)
```
[ WARNING ]: Specify poToken for stable and fast operation. See README for details.
[  INFO!  ]: Automatically generates poToken, but stable operation cannot be guaranteed.
```
And then it panic and crash

## Environment

- Video URL: https://www.youtube.com/watch?si=RGj8VD51j4-mQZ5w&v=iT_e4-gXLt0&feature=youtu.be
- @ybd-project/ytdl-core version: 5.0.12
- Node.js version: v22.7.0
- Operating system: macOS

**Comment by ybd-project** [comment] 2024-09-05 08:31
Thank you for your report. As known, you need to specify PoToken and VisitorData to get information from YouTube.
It works locally without these, but not on AWS VPS, etc.
Please refer to the README for details on how to obtain these.

**Comment by ybd-project** [comment] 2024-09-05 08:34
Thank you for your report. We will investigate this issue and take appropriate action.

**Comment by ybd-project** [comment] 2024-09-05 10:09
This problem may be caused by information from getBasicInfo being passed to the downloadFromInfo function.
The downloadFromInfo function needs to be passed the information from the getInfo function.

**Comment by ybd-project** [comment] 2024-09-07 12:44
Is the problem resolved?

**Comment by iRajatDas** [comment] 2024-09-09 05:20
> Is the problem resolved?

Quick question, Do we need to generate a `po_token` everytime we call it?

**Comment by ybd-project** [comment] 2024-09-09 05:57
> Quick question, Do we need to generate a `po_token` everytime we call it?

No need. I have 200~300 requests per 30 minutes on my API and it works with the same PoToken.

**Comment by ybd-project** [comment] 2024-09-09 05:59
We have determined that this issue is not a ytdl-core issue and will close it. If you have any questions, please create the issue again.

**Closed by ybd-project** 2024-09-09 05:59 UTC
Labels: bug
