### ISSUE TITLE
Proxies and Mp3

### ISSUE THREAD

**Issue by VenomSA** [ybd-project/ytdl-core#17] opened 2024-09-10 21:23 UTC
I need an example on how to use proxies on this updated package.

```
const ytdl = new YtdlCore({
    agent: ytdl.createProxyAgent({ uri: 'my.proxy.server' }),
});
```

This throws 'Can't access ytdl before initialisation' which is correct.

Also, would be nice to know how to turn videos to mp3, distube repo had the audioonly filter but for this package I couldn't find anything similar, so any help would be appreciated! 

And sorry if I created an issue with the purpose of asking questions.

**Comment by ybd-project** [comment] 2024-09-10 21:38
Change ytdl to the YtdlCore class. It can be used as a static method.

**Comment by ybd-project** [comment] 2024-09-11 12:12
Is the problem resolved?
If you continue to receive no reply, I will close this issue as resolved.

**Comment by VenomSA** [comment] 2024-09-12 10:42
const ytdl = new YtdlCore({
                agent: YtdlCore.createProxyAgent({ uri: getRandomProxyAgent() }),
            });
            
            Ok I managed to do this and its working, and how to apply the audioonly filter for mp3 download now?
            
            Before I had something like this
            
            `const audioStream = ytdl(videoURL, { filter: "audioonly" });
            
            const chunks = [];

            audioStream.on("data", (chunk) => {
                chunks.push(chunk);
            });

            audioStream.on("end", () => {
                const buffer = Buffer.concat(chunks);
                resolve({ base64: buffer.toString("base64"), title: videoTitle });
            });

            audioStream.on("error", (err) => {
                reject(err);
            });`

**Comment by VenomSA** [comment] 2024-09-12 10:43
I managed to do this and it's working, but how can I apply the audio-only filter in order to download only mp3?

`            const ytdl = new YtdlCore({
                agent: YtdlCore.createProxyAgent({ uri: getRandomProxyAgent() }),
            });
            
            Ok I managed to do this and its working, and how to apply the audioonly filter for mp3 download now?
            
            Before I had something like this
            
            `const audioStream = ytdl(videoURL, { filter: "audioonly" });
            
            const chunks = [];

            audioStream.on("data", (chunk) => {
                chunks.push(chunk);
            });

            audioStream.on("end", () => {
                const buffer = Buffer.concat(chunks);
                resolve({ base64: buffer.toString("base64"), title: videoTitle });
            });

            audioStream.on("error", (err) => {
                reject(err);
            });`
            
            `

**Comment by ybd-project** [comment] 2024-09-12 10:46
https://github.com/ybd-project/ytdl-core/tree/main/examples/Download
Please refer to this.

**Comment by VenomSA** [comment] 2024-09-12 10:49
Thank you! You can close it.

**Comment by ybd-project** [comment] 2024-09-12 10:50
The issue has been resolved and the issue is closed.

**Closed by ybd-project** 2024-09-12 10:50 UTC
Labels: bug
