### ISSUE TITLE
Unhandled Rejection: TypeError: Cannot read properties of undefined (reading 'thumbnails')   

### ISSUE THREAD

**Issue by kimgh06** [ybd-project/ytdl-core#1] opened 2024-08-20 08:17 UTC
## Describe the bug

When I try to get a video via ytdl() on serverless deployments.
```
Unhandled Rejection: TypeError: Cannot read properties of undefined (reading 'thumbnails')
    at Object.k [as cleanVideoDetails] (/var/task/.next/server/app/api/get_video/route.js:1:28364)
    at P (/var/task/.next/server/app/api/get_video/route.js:3:377)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```
## Environment

- @ybd-project/ytdl-core version:^5.0.1-test.4"
- Node.js version: 20
- Operating system: Linux

**Comment by ybd-project** [comment] 2024-08-20 08:20
Thank you for your report. We are currently identifying the cause of the bug and fixing it.

**Comment by ybd-project** [comment] 2024-08-20 08:31
Version v5.0.3, which appears to fix this bug, is now available.
Please try it.

**Comment by kimgh06** [comment] 2024-08-20 08:39
Ok, I tried it and another bug appears.

```
Unhandled Rejection: InvalidArgumentError: invalid url
    at /var/task/node_modules/undici/index.js:57:13
    at Object.f [as request] (/var/task/.next/server/app/api/get_video/route.js:6:4436)
    at /var/task/.next/server/app/api/get_video/route.js:6:217
    at i.getOrSet (/var/task/.next/server/app/api/get_video/route.js:1:7818)
    at O (/var/task/.next/server/app/api/get_video/route.js:6:172)
    at Object.D [as decipherFormats] (/var/task/.next/server/app/api/get_video/route.js:6:851)
    at L (/var/task/.next/server/app/api/get_video/route.js:3:848)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UND_ERR_INVALID_ARG'
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

**Comment by ybd-project** [comment] 2024-08-20 08:40
That has been fixed in v5.0.4. Please try a fresh install.

**Comment by kimgh06** [comment] 2024-08-20 08:41
Oh, I will

**Comment by ybd-project** [comment] 2024-08-20 08:45
Also, v5.0.4 contains useless logs and data. v5.0.5 should be installed.

**Comment by kimgh06** [comment] 2024-08-20 08:48
Checked it.

**Comment by ybd-project** [comment] 2024-08-20 08:49
> Checked it.

Is it working?

**Comment by kimgh06** [comment] 2024-08-20 08:50
No, another bug appears on vercel.
```
Unhandled Rejection: Error: This video is unavailable
    at y (/var/task/.next/server/app/api/get_video/route.js:1:20233)
    at /var/task/.next/server/app/api/get_video/route.js:1:22211
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

**Comment by ybd-project** [comment] 2024-08-20 08:52
What is the video URL?

**Comment by kimgh06** [comment] 2024-08-20 08:52
And here are warning messages.
![image](https://github.com/user-attachments/assets/d0d19617-5595-4a13-97c1-3375ae15195c)

**Comment by kimgh06** [comment] 2024-08-20 08:53
> What is the video URL?

https://www.youtube.com/watch?v=oMfMUfgjiLg
G N R - Sweet child o' mine

**Comment by ybd-project** [comment] 2024-08-20 08:53
> And here are warning messages. ![image](https://private-user-images.githubusercontent.com/101877146/359407402-d0d19617-5595-4a13-97c1-3375ae15195c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDQyNTAsIm5iZiI6MTcyNDE0Mzk1MCwicGF0aCI6Ii8xMDE4NzcxNDYvMzU5NDA3NDAyLWQwZDE5NjE3LTU1OTUtNGExMy05N2MxLTMzNzVhZTE1MTk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwODUyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDFkOWY4NjMzZDZhNjVjZThhNmYwNTNjYjUyMjdlMWM0MjU2NzFlNDE1MDVlYWM4ZDI5ZDQzODRjYjVhMTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ISNtMfwt7E75Wqy7M_hOqXzkaIfAye2u6WPm1Z06Lj8)

It is normal. Currently, iOS and Android players will output that log because of the error.

**Comment by ybd-project** [comment] 2024-08-20 08:54
> > What is the video URL?
> 
> https://www.youtube.com/watch?v=oMfMUfgjiLg G N R - Sweet child o' mine

Do you specify a `poToken`?

**Comment by kimgh06** [comment] 2024-08-20 08:55
Yes, I did.
```js
const stream = ytdl(`https://youtube.com/watch?v=${url}`, {
          agent,
          filter: 'audioonly',
          quality: 'highestaudio',
          format: 'mp3',
          poToken,
          visitorData
        }).on('error', e => {
          console.log(e, 'error at get_video')
          throw e;
        });
```

**Comment by ybd-project** [comment] 2024-08-20 08:56
Try generating a new one.
Also, what is specified in the agent?

**Comment by kimgh06** [comment] 2024-08-20 08:59
The agent for cookies.
```js
const cookies = [{
          "domain": ".youtube.com",
          "expirationDate": 1956442831.220501,
          "hostOnly": false,
          "httpOnly": true,
          "name": "__Secure-1PSID",
          "path": "/",
          "sameSite": "unspecified",
          "secure": true,
          "session": false,
          "storeId": "0",
          "value": "g.a000mAgEOqoSd3RlbdBjNWAGnCWmcFtdOYwMaAYNJhfnnAyqaONtGaKgncRerL0dDxPwwp8sGQACgYKAZcSARUSFQHGX2MiaMV9LPBojznMJKAJiJcXyBoVAUF8yKqTxm8uenq1M5aIWXtBZrX00076",
          "id": 2
        },]
        const agent = ytdl.createAgent(cookies)
```

and I try generate new one and will reply.

**Comment by ybd-project** [comment] 2024-08-20 09:01
Please do not specify cookies.

**Comment by kimgh06** [comment] 2024-08-20 09:02
Ok.

**Comment by kimgh06** [comment] 2024-08-20 09:05
I applied my new token on serverless environment variables, but same error appears on logs.

```
Unhandled Rejection: Error: This video is unavailable
    at y (/var/task/.next/server/app/api/get_video/route.js:1:19869)
    at /var/task/.next/server/app/api/get_video/route.js:1:21847
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

**Comment by ybd-project** [comment] 2024-08-20 09:14
Glitch and Vercel Functions do not generate errors, so it is possible that the `poToken` and `visitorData` are incorrect, either due to geographical factors or because the `poToken` and `visitorData` are incorrect.

Vercel: https://ytdl-core-test.vercel.app/api/v3/info/full/?videoUrl=https://youtu.be/oMfMUfgjiLg
Glitch: http://marsh-numerous-oak.glitch.me/stream/basic/?ytid=oMfMUfgjiLg

**Comment by ybd-project** [comment] 2024-08-20 10:41
The issue has been resolved and the issue is closed.

**Closed** 2024-08-20 10:41 UTC
Labels: bug

**Comment by kimgh06** [comment] 2024-08-20 11:19
My Biggest mistake.
![image](https://github.com/user-attachments/assets/7a8dfb84-cc27-4775-9a8b-af110bd283ba)
![image](https://github.com/user-attachments/assets/4b32befb-5679-4fa3-a9e8-d40a36e49ea3)

And Thanks!
