### ISSUE TITLE
can you give an example that convert video to audio

### ISSUE THREAD

**Issue by td236** [ybd-project/ytdl-core#15] opened 2024-09-09 08:52 UTC
it is appreciated that
i tried to convert, but throw an error

throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg

**Comment by ybd-project** [comment] 2024-09-09 08:56
By video to audio, do you mean converting videos that contain audio?

**Comment by td236** [comment] 2024-09-09 08:59
Actually, I just need the audio

**Comment by ybd-project** [comment] 2024-09-09 09:00
If so, what code are you implementing?

**Comment by td236** [comment] 2024-09-09 09:04
https://github.com/fent/node-ytdl-core/blob/master/example/convert_to_mp3.js

I used this before, but it does not work due to cookies

**Comment by td236** [comment] 2024-09-09 09:07
> If so, what code are you implementing? There is an audio-only format, so there is no need to convert if you use that.

ok i`ll try it

**Comment by ybd-project** [comment] 2024-09-09 09:07
> https://github.com/fent/node-ytdl-core/blob/master/example/convert_to_mp3.js
> 
> I used this before, but it does not work due to cookies

ok. please wait while i create an example implementation now.

**Comment by td236** [comment] 2024-09-09 09:08
> > https://github.com/fent/node-ytdl-core/blob/master/example/convert_to_mp3.js
> > I used this before, but it does not work due to cookies
> 
> ok. please wait while i create an example implementation now.

really appreciate

**Comment by ybd-project** [comment] 2024-09-09 09:58
Have you run npm install?
Run the example code once (copying package.json as well).

**Comment by ybd-project** [comment] 2024-09-09 10:00
This could be a problem with ffmpeg, as it works fine in my environment.
Can I close this issue?

**Comment by td236** [comment] 2024-09-09 10:01
> Have you run npm install? Run the example code once (copying package.json as well).

yeah i did that

**Comment by td236** [comment] 2024-09-09 10:01
> This could be a problem with ffmpeg, as it works fine in my environment. Can I close this issue?

ok

**Closed** 2024-09-09 10:02 UTC
Labels: feature

**Comment by td236** [comment] 2024-09-10 08:32
hi, the audio I downloaded with this method is blank

`YtdlCore.getFullInfo('https://www.youtube.com/watch?v=92tyqChI878').then((info) => {

    let audioFormats = YtdlCore.filterFormats(info.formats, "audioonly");
    const format = YtdlCore.chooseFormat(audioFormats, { quality: "highestaudio" });
    const fileName = `./audio/test.${format.container}`;
    
    ytdl.downloadFromInfo(info, { format })
        .pipe(fs.createWriteStream(fileName));

});`

**Comment by ybd-project** [comment] 2024-09-10 08:47
It downloads fine in my environment. Is the environment in which it is running local?

**Comment by td236** [comment] 2024-09-10 08:51
Yes, locally,
It was normal before the last step - ytdl.downloadFromInfo..

**Comment by ybd-project** [comment] 2024-09-10 09:00
What format data is retrieved by the chooseFormat function?

**Comment by td236** [comment] 2024-09-10 09:04
![image](https://github.com/user-attachments/assets/13319b6a-82c7-45f2-984c-659f0bff8557)

.webm

can obtain format information normally

**Comment by ybd-project** [comment] 2024-09-10 09:10
During the download process, 0KB is displayed, but is the process completed successfully?

**Comment by td236** [comment] 2024-09-10 09:13
i think so 
no error was thrown

**Comment by ybd-project** [comment] 2024-09-10 09:26
It is working fine in my environment, so it may be a network issue.

**Comment by td236** [comment] 2024-09-10 09:34
```
// Download a video
ytdl.download('https://www.youtube.com/watch?v=92tyqChI878').pipe(fs.createWriteStream('video.mp4'));
```

but i can download this video with this successfully

**Comment by ybd-project** [comment] 2024-09-10 09:46
Can you change the code to this and try it?
```ts
YtdlCore.getFullInfo('https://www.youtube.com/watch?v=92tyqChI878').then((info) => {

    let audioFormats = YtdlCore.filterFormats(info.formats, "audioonly");
    const format = YtdlCore.chooseFormat(audioFormats, { quality: 'highestaudio', filteringClients: ['webCreator', 'ios', 'android'] });
    const fileName = `./audio/test.${format.container}`;
    
    ytdl.downloadFromInfo(info, { format })
        .pipe(fs.createWriteStream(fileName));
});
```

**Comment by td236** [comment] 2024-09-11 03:08
hi sir
the two ways:
1 config audioonly - get blank file
2 convert  implementation - i resolved the issue with ffmpeg, but can not get the stream, is the download function returning a promise instance?
![image](https://github.com/user-attachments/assets/49fa5391-cf7d-4670-8173-cf5f03b0faf7)

**Comment by td236** [comment] 2024-09-11 03:09
> Can you change the code to this and try it?
> 
> ```ts
> YtdlCore.getFullInfo('https://www.youtube.com/watch?v=92tyqChI878').then((info) => {
> 
>     let audioFormats = YtdlCore.filterFormats(info.formats, "audioonly");
>     const format = YtdlCore.chooseFormat(audioFormats, { quality: 'highestaudio', filteringClients: ['webCreator', 'ios', 'android'] });
>     const fileName = `./audio/test.${format.container}`;
>     
>     ytdl.downloadFromInfo(info, { format })
>         .pipe(fs.createWriteStream(fileName));
> });
> ```

i tried, still blank file

**Comment by ybd-project** [comment] 2024-09-11 06:03
I think this is not a problem with ytdl-core, but with the environment in which it is running.
Can you tell me what operating system you are using?

**Comment by td236** [comment] 2024-09-11 06:37
Windows 11 Professional Edition

**Comment by ybd-project** [comment] 2024-09-11 06:43
You are just like me...
We are working on improvements regarding format selection in v5.1.2 now, so please wait for the release. (We will release it today...)
Also, is this problem happening with all videos?

**Comment by td236** [comment] 2024-09-11 06:57
![image](https://github.com/user-attachments/assets/fae7b8b6-a8cf-4115-ba47-92eb7d7da2fb)
i found one that can be downloaded and played normally

**Comment by ybd-project** [comment] 2024-09-11 06:59
Also, one thing that concerns me is that it is saved in webm.

**Comment by td236** [comment] 2024-09-11 07:13
it seems that short videos can be downloaded normally

**Comment by ybd-project** [comment] 2024-09-11 07:18
Then the 0KB ones may be in the process of downloading. If so, the problem is with your network.

**Comment by td236** [comment] 2024-09-19 08:56
`const { YtdlCore } = require('@ybd-project/ytdl-core');`
this code does not work on Linux

**Comment by ybd-project** [comment] 2024-09-19 09:07
What is name and version?
In my testing, I am running on Ubuntu 22.04 and 24.04 and CentOS 9.

**Comment by td236** [comment] 2024-09-19 09:15
sorry sir 
it works now
it takes a lot time to launch
